creating neural networks from scratch



working on same mnist data set to predict the no. from dataset which have the numbers photos

simple 28*28 pixels total 784, images so we uses a simple NN that look like
3 layers - 1) 784 input neurons for each pixels
           2) hidden layer- 10 neurons
           3) 10 neurons one more layer giving me y^

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data  = pd.read_csv('train.csv')
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
data = np.array(data)
m,n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
y_dev = data_dev[0]
x_dev = data_dev[1:n]

data_train = data[1000:m].T
y_train = data_train[0]
x_train = data_train[1:n]

#normalizing the data

x_train = x_train / 255.0
x_dev = x_dev / 255.0



In [ ]:
x_train[:, 0].shape

(784,)

In [ ]:
def init_parameters():
  w1 = np.random.rand(10, 784) * 0.01
  b1 = np.zeros((10, 1))
  w2 = np.random.rand(10, 10) * 0.01
  b2 = np.zeros((10, 1))
  return w1, b1, w2, b2



def relu(z):
  return np.maximum(0,z)

def softmax(z):
  exp_z = np.exp(z - np.max(z,axis=0,keepdims=True))
  return exp_z / np.sum(exp_z,axis=0,keepdims=True)

def forward_prop(w1,b1,w2,b2,x):
  z1 = w1.dot(x) + b1
  a1 = relu(z1)
  z2 = w2.dot(a1) + b2
  a2 = softmax(z2)
  return z1,a1,z2,a2

def one_hot(y):
  one_hot_y = np.zeros((y.size,int(y.max()+1)))
  one_hot_y[np.arange(y.size),y.astype(int)] = 1
  one_hot_y = one_hot_y.T
  return one_hot_y

def deriv_relu(z):
  return z > 0


def back_prop(z1,a1,z2,a2,x,y,w2):
  m = y.size
  one_hot_y = one_hot(y)
  dz2 = a2 - one_hot_y
  dw2 = (1 / m) * np.dot(dz2, a1.T)
  db2 = (1 / m) * np.sum(dz2, axis=1, keepdims=True)

  dz1 = np.dot(w2.T, dz2) * deriv_relu(z1)
  dw1 = (1 / m) * np.dot(dz1, x.T)
  db1 = (1 / m) * np.sum(dz1, axis=1, keepdims=True)
  return dw1,db1,dw2,db2

def update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha):
  w1 = w1 - alpha * dw1
  b1 = b1 - alpha * db1
  w2 = w2 - alpha * dw2
  b2 = b2 - alpha * db2
  return w1,b1,w2,b2






In [ ]:
def get_pred(a2):
  return np.argmax(a2,0)

def get_accur(predictions,y):
  print(predictions,y)
  return np.sum(predictions == y) / y.size

def gradient_decent(x,y,iterations,alpha):
  w1,b1,w2,b2 = init_parameters()
  for i in range(iterations):
    z1,a1,z2,a2 = forward_prop(w1 , b1, w2, b2, x)
    dw1,db1,dw2,db2 = back_prop(z1, a1, z2, a2, x, y, w2)
    w1, b1, w2, b2 = update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha)

    if i % 100 == 0:
      print("iteration: ",i)
      print("accuracy: ",get_accur(get_pred(a2),y))
  return w1,b1,w2,b2


In [ ]:
w1,b1,w2,b2 = gradient_decent(x_train,y_train,1000,0.01)

iteration:  0
[2 2 2 ... 2 2 2] [9 1 3 ... 2 7 9]
accuracy:  0.09970731707317074
iteration:  100
[0 0 0 ... 0 0 0] [9 1 3 ... 2 7 9]
accuracy:  0.09848780487804878
iteration:  200
[0 0 0 ... 0 0 0] [9 1 3 ... 2 7 9]
accuracy:  0.09851219512195122
iteration:  300
[0 0 0 ... 0 0 0] [9 1 3 ... 2 7 9]
accuracy:  0.10936585365853659
iteration:  400
[0 1 0 ... 0 3 0] [9 1 3 ... 2 7 9]
accuracy:  0.175390243902439
iteration:  500
[1 1 0 ... 0 1 0] [9 1 3 ... 2 7 9]
accuracy:  0.20095121951219513
iteration:  600
[1 1 0 ... 0 1 0] [9 1 3 ... 2 7 9]
accuracy:  0.21439024390243902
iteration:  700
[1 1 0 ... 0 1 0] [9 1 3 ... 2 7 9]
accuracy:  0.22160975609756098
iteration:  800
[1 1 0 ... 0 1 0] [9 1 3 ... 2 7 9]
accuracy:  0.23746341463414633
iteration:  900
[1 1 0 ... 0 1 0] [9 1 3 ... 2 7 9]
accuracy:  0.27719512195121954
